site_name: Finn Stainton
theme:
  name: material
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/
    - icon: fontawesome/brands/github
      link: https://github.com/finn-stainton
copyright: Copyright &copy; 2021 Finn Stainton
