# Project information
site_name: Finn Stainton
site_url: https://finn-stainton.github.io/
site_author: Finn Stainton
site_description: >-
  Welcome to my second brain, working notes, ideas and on-going project write ups. 
  This website is inspired by <i>working with the garage door up</i> mentality of being open with the current state projects, knowledge and problems I'm pondering.

repo_url: https://github.com/finn-stainton/finn-stainton.github.io
repo_name: finn-stainton.github.io

copyright: >-
  <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">
  <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />
  This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">
  Creative Commons Attribution 4.0 International License</a>. I cannot guarantee all content will be free of errors or copyright protections. 

theme:
  name: material
  custom_dir: material
  palette:
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/library
  features:
    - navigation.instant
    - navigation.tabs
    # - navigation.indexes
    # - navigation.sections
plugins:
  - search
  - git-revision-date
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/finn-stainton-202525214
    - icon: fontawesome/brands/github
      link: https://github.com/finn-stainton

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences 
  - footnotes
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html

# nav:
#   - Home:
#     - index.md
#   - Knowledge:
#     - knowledge/index.md
#     - Software: 
#       - knowledge/Software/index.md
#     - Hardware: 
#       - knowledge/Hardware/index.md
#     - Mathematics: 
#       - knowledge/Mathematics/index.md
#   - Project:
#     - projects/index.md
#   - Thoughts:
#     - thoughts/index.md
#   - Misc:
#     - misc/index.md

