# Project information
site_name: Finn Stainton
site_url: https://finn-stainton.github.io/
site_author: Finn Stainton
site_description: >-
  Personal Website

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
  features:
    - navigation.instant
    - navigation.tabs
    # - navigation.indexes
    - toc.integrate
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/finn-stainton-202525214
    - icon: fontawesome/brands/github
      link: https://github.com/finn-stainton
copyright: Copyright &copy; 2021 Finn Stainton. I cannot guarantee all content will be free of errors or copyright protections. 

# nav:
#   - Home:
#     - index.md
#   - Knowledge:
#     - knowledge/index.md
#     - Software: 
#       - knowledge/Software/index.md
#     - Hardware: 
#       - knowledge/Hardware/index.md
#     - Mathematics: 
#       - knowledge/Mathematics/index.md
#   - Project:
#     - projects/index.md
#   - Thoughts:
#     - thoughts/index.md
#   - Misc:
#     - misc/index.md

